### ISSUE TITLE
Let's de-duplicate Alien::libtiff

### ISSUE THREAD

**Issue by plicease** [shawnlaffan/perl-alien-libtiff#1]
I've been working with @carygravel, mostly via email on implementing his own Alien::libtiff, and I just realized there is already a Alien::libtiff on cpan, and it looks like it is working pretty well.  @shawnlaffan I think it would be good to de-duplicate some work here and see if we can help get him get `Graphics::TIFF` working with the existing `Alien::libtiff`.

There may be a linker error getting `Graphics::TIFF` working on Windows, but I am not entirely clear on which version of `Alien::libtiff`, or the broader context for this error, hopefully @carygravel can provide some additional insight:

```
(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 5 exit status
``

**Comment by carygravel** [comment]
Before I started working on an Alien::libtiff, I _did_ check whether something already existed, but evidently not well enough, because I only found Shawn's when I tried to upload my own and PAUSE said I didn't have permission. Needless to say, I've deleted what I tried to upload to CPAN, and I'll delete the Github repo as soon as I have Graphics::TIFF compiling against Shawn's Alien::libtiff.

**Comment by carygravel** [comment]
After some help from @PhilterPaper I found that adding `-mdll` to the linker flags fixes the above `WinMain` error, but at least in the Github CI, the `collect2.exe: error: ld returned 5 exit status` [still remains](https://github.com/carygravel/graphics-tiff/actions/runs/870384443).

@PhilterPaper has been [able to compile locally](https://github.com/carygravel/graphics-tiff/issues/3).

But I am stuck and running out of ideas.

**Comment by PhilterPaper** [comment]
That would be a bummer to have put all that work into Alien::libtiff and _then_ find out there's already one out there! If the old one turns out to work at least as well as Cary's new one, then by all means use the old one, but if the new one is better, maybe you can work with Shawn to update the existing Alien::libtiff with the best of both worlds.

**Comment by shawnlaffan** [comment]
I'm open to working together on this.  It could be via PRs, or using an organisation for the repo.  The version by @carygravel has extra tests that my version lacks (all I check atm is that it compiles). 

As for the compilation issues, past experience with GH workflows is that the Git for Windows ```usr/bin``` path can often interfere with compilation of aliens.  This is why Alien::gdal, for example, strips out any such paths before it builds: https://github.com/shawnlaffan/perl-alien-gdal/blob/81b32e7f80c8191033aec1039eb7658c80cc5209/alienfile#L378

Similar issues might be affecting Graphics::TIFF.  For example, the workflow log linked to above refers to gcc toolchain files from mingw instead of those provided with Strawberry perl.

**Comment by shawnlaffan** [comment]
Also, workflow files need to ensure that the Strawberry perl bin dirs are at the front of the path.

For example:
https://github.com/shawnlaffan/perl-alien-gdal/blob/81b32e7f80c8191033aec1039eb7658c80cc5209/.github/workflows/windows.yml#L30

I will update the Alien::libtiff workflow shortly, as it uses the old syntax.

**Comment by PhilterPaper** [comment]
Wait a minute. Before installing the latest Graphics::TIFF, I used CPAN (on Windows, Strawberry Perl) to install "Alien::libtiff" (Graphics::TIFF had refused to install until this was done). Did I actually install the old (Shawn's) system, or the new one (Cary's)? BTW, I already had manually copied in libtiff version 4.0.10 into the Strawberry libraries, and it's still there (Alien::libtiff seems to claim that it was building 4.0.7). `Graphics::TIFF->get_version` says it's seeing 4010.

CPAN says it's SLAFFAN/Alien-libtiff-1.01.tar.gz, which I guess is Shawn's.

**Comment by shawnlaffan** [comment]
I just ran a build of Graphics::TIFF from the head of the Windows branch, using Strawberry perl 5.28.0 with a current install of Alien::libtiff.

It all ran smoothly, including the tests.  All the gcc utilities being called were from Strawberry perl.

I strongly suspect the workflow errors are path related, caused by mixing of msys2 and strawberry utilities.

**Comment by shawnlaffan** [comment]
```cmd
C:\path\graphics-tiff>perl Makefile.PL
Checking if your kit is complete...
Looks good
Generating a gmake-style Makefile
Writing Makefile for Graphics::TIFF
Writing MYMETA.yml and MYMETA.json

C:\path\graphics-tiff>gmake
cp lib/Graphics/TIFF.pm blib\lib\Graphics\TIFF.pm
Running Mkbootstrap for TIFF ()
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" -MExtUtils::Command -e chmod -- 644 "TIFF.bs"
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- TIFF.bs blib\arch\auto\Graphics\TIFF\TIFF.bs 644
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" "C:\berrybrew\5.28.0_64_PDL\perl\lib\ExtUtils/xsubpp"  -typemap C:\berrybrew\5.28.0_64_PDL\perl\lib\ExtUtils\typemap -typemap C:\path\graphics-tiff\typemap  TIFF.xs > TIFF.xsc
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" -MExtUtils::Command -e mv -- TIFF.xsc TIFF.c
gcc -c  -I. -IC:\berrybrew\5.28.0_64_PDL\c\include -s -O2 -Wl,--verbose  -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields -s -O2   -DVERSION=\"12\" -DXS_VERSION=\"12\"  "-IC:\berrybrew\5.28.0_64_PDL\perl\lib\CORE"  -DCONSERVATIVE TIFF.c
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" -MExtUtils::Mksymlists \
     -e "Mksymlists('NAME'=>\"Graphics::TIFF\", 'DLBASE' => 'TIFF', 'DL_FUNCS' => {  }, 'FUNCLIST' => [], 'IMPORTS' => {  }, 'DL_VARS' => []);"
g++.exe TIFF.def -o blib\arch\auto\Graphics\TIFF\TIFF.xs.dll --verbose -mdll -s -L"C:\berrybrew\5.28.0_64_PDL\perl\lib\CORE" -L"C:\berrybrew\5.28.0_64_PDL\c\lib" TIFF.o   "C:\berrybrew\5.28.0_64_PDL\perl\lib\CORE\libperl528.a" "C:\berrybrew\5.28.0_64_PDL\c\lib\libtiff.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libmoldname.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libkernel32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libuser32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libgdi32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libwinspool.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libcomdlg32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libadvapi32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libshell32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libole32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\liboleaut32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libnetapi32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libuuid.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libws2_32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libmpr.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libwinmm.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libversion.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libodbc32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libodbccp32.a" "C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libcomctl32.a" -Wl,--enable-auto-image-base
Using built-in specs.
COLLECT_GCC=g++.exe
COLLECT_LTO_WRAPPER=C:/berrybrew/5.28.0_64_PDL/c/bin/../libexec/gcc/x86_64-w64-mingw32/7.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-7.1.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-mpc=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-isl=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh, Built by strawberryperl.com project' CFLAGS='-O2 -pipe -fno-ident -I/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS=' -I/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/opt/build/x86_64-710-posix-seh-rt_v502/mingw64/opt/lib -L/opt/build/prerequisites/x86_64-zlib-static/lib -L/opt/build/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 7.1.0 (x86_64-posix-seh, Built by strawberryperl.com project)
COMPILER_PATH=C:/berrybrew/5.28.0_64_PDL/c/bin/../libexec/gcc/x86_64-w64-mingw32/7.1.0/;C:/berrybrew/5.28.0_64_PDL/c/bin/../libexec/gcc/;C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/bin/
LIBRARY_PATH=C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/;C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/;C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/lib/../lib/;C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../lib/;C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/lib/;C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../
COLLECT_GCC_OPTIONS='-o' 'blib\arch\auto\Graphics\TIFF\TIFF.xs.dll' '-v' '-mdll' '-s' '-LC:\berrybrew\5.28.0_64_PDL\perl\lib\CORE' '-LC:\berrybrew\5.28.0_64_PDL\c\lib' '-shared-libgcc' '-mtune=core2' '-march=nocona'
 C:/berrybrew/5.28.0_64_PDL/c/bin/../libexec/gcc/x86_64-w64-mingw32/7.1.0/collect2.exe -plugin C:/berrybrew/5.28.0_64_PDL/c/bin/../libexec/gcc/x86_64-w64-mingw32/7.1.0/liblto_plugin-0.dll -plugin-opt=C:/berrybrew/5.28.0_64_PDL/c/bin/../libexec/gcc/x86_64-w64-mingw32/7.1.0/lto-wrapper.exe -plugin-opt=-fresolution=C:\Users\user\AppData\Local\Temp\ccQfh8rU.res -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-ladvapi32 -plugin-opt=-pass-through=-lshell32 -plugin-opt=-pass-through=-luser32 -plugin-opt=-pass-through=-lkernel32 -plugin-opt=-pass-through=-liconv -plugin-opt=-pass-through=-lmingw32 -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lmoldname -plugin-opt=-pass-through=-lmingwex -plugin-opt=-pass-through=-lmsvcrt -m i386pep --dll -Bdynamic -e DllMainCRTStartup --enable-auto-image-base -o blib\arch\auto\Graphics\TIFF\TIFF.xs.dll -s C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/lib/../lib/dllcrt2.o C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/crtbegin.o -LC:\berrybrew\5.28.0_64_PDL\perl\lib\CORE -LC:\berrybrew\5.28.0_64_PDL\c\lib -LC:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0 -LC:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc -LC:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/lib/../lib -LC:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../lib -LC:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../../../x86_64-w64-mingw32/lib -LC:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/../../.. TIFF.def TIFF.o C:\berrybrew\5.28.0_64_PDL\perl\lib\CORE\libperl528.a C:\berrybrew\5.28.0_64_PDL\c\lib\libtiff.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libmoldname.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libkernel32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libuser32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libgdi32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libwinspool.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libcomdlg32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libadvapi32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libshell32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libole32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\liboleaut32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libnetapi32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libuuid.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libws2_32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libmpr.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libwinmm.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libversion.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libodbc32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libodbccp32.a C:\berrybrew\5.28.0_64_PDL\c\x86_64-w64-mingw32\lib\libcomctl32.a --enable-auto-image-base -lstdc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -liconv -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt C:/berrybrew/5.28.0_64_PDL/c/bin/../lib/gcc/x86_64-w64-mingw32/7.1.0/crtend.o
COLLECT_GCC_OPTIONS='-o' 'blib\arch\auto\Graphics\TIFF\TIFF.xs.dll' '-v' '-mdll' '-s' '-LC:\berrybrew\5.28.0_64_PDL\perl\lib\CORE' '-LC:\berrybrew\5.28.0_64_PDL\c\lib' '-shared-libgcc' '-mtune=core2' '-march=nocona'
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" -MExtUtils::Command -e chmod -- 755 blib\arch\auto\Graphics\TIFF\TIFF.xs.dll

C:\path\graphics-tiff>gmake test
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- TIFF.bs blib\arch\auto\Graphics\TIFF\TIFF.bs 644
"C:\berrybrew\5.28.0_64_PDL\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/1.t ............ ok
t/2.t ............ ok
t/8_enums.t ...... ok
t/90_MANIFEST.t .. 'egrep' is not recognized as an internal or external command,
operable program or batch file.
t/90_MANIFEST.t .. ok
t/91_critic.t .... skipped: Author test.  Set $ENV{TEST_AUTHOR} to a true value to run.
t/92_tiffinfo.t .. skipped: Test requires module 'Image::Magick' but it's not found
t/93_tiff2pdf.t .. skipped: Test requires module 'Image::Magick' but it's not found
All tests successful.
Files=7, Tests=215,  3 wallclock secs ( 0.08 usr +  0.05 sys =  0.12 CPU)
Result: PASS
```

**Comment by PhilterPaper** [comment]
Good to know that Windows installation (Strawberry Perl) works fine for someone else. I have talked to Cary about some t-test fixes for "90" to get around the 'egrep' error. As for the Windows CI (workflow) issues, it could very well be a problem with mixing sources, although that might not explain why Cary and I see different errors in CI. Look at carygravel/graphics-tiff 'actions' vs. PhilterPaper/graphics-tiff 'actions'. Anyway, discussion about that probably belongs on carygravel/graphics-tiff rather than here.

By the way, if Alien is being used to prereq libtiff, shouldn't CPAN try to install Alien::libtiff automatically, rather than requiring me to manually initiate the install? I.e., `cpan> install Alien::libtiff` before `cpan> install Graphics::TIFF`.

**Comment by carygravel** [comment]
> Wait a minute. Before installing the latest Graphics::TIFF, I used CPAN (on Windows, Strawberry Perl) to install "Alien::libtiff" (Graphics::TIFF had refused to install until this was done). Did I actually install the old (Shawn's) system, or the new one (Cary's)? BTW, I already had manually copied in libtiff version 4.0.10 into the Strawberry libraries, and it's still there (Alien::libtiff seems to claim that it was building 4.0.7). `Graphics::TIFF->get_version` says it's seeing 4010.
> 
> CPAN says it's SLAFFAN/Alien-libtiff-1.01.tar.gz, which I guess is Shawn's.

Yup. The work I did never made it to CPAN.

**Comment by carygravel** [comment]
> Also, workflow files need to ensure that the Strawberry perl bin dirs are at the front of the path.
> 
> For example:
> https://github.com/shawnlaffan/perl-alien-gdal/blob/81b32e7f80c8191033aec1039eb7658c80cc5209/.github/workflows/windows.yml#L30

That was the solution! Thanks. [All working now](https://github.com/carygravel/graphics-tiff/actions/runs/875335207).

**Comment by carygravel** [comment]
I've got two actions, one with `set ALIEN_INSTALL_TYPE=share` and one without. The output seems to be identical, so I assume this is having no effect. How can I force shared or system installations?

**Comment by plicease** [comment]
> I've got two actions, one with `set ALIEN_INSTALL_TYPE=share` and one without. The output seems to be identical, so I assume this is having no effect. How can I force shared or system installations?

setting `ALIEN_INSTALL_TYPE=system` should "force" a system install; that is it will use the system libs if found and fail if not.
setting `ALIEN_INSTALL_TYPE=default` or leaving it unset will use the system libs if found and a share install if not.

So I would expect if you have a action where `ALIEN_INSTALL_TYPE` is unset and it is still doing a share install it means it isn't finding the system library.

**Comment by shawnlaffan** [comment]
Environment variables don't persist outside the individual run calls.  The set call needs to be in the same run as the cpan calls.  

Something like this (I put the Alien::libtiff call on its own line for clarity only)
```yaml
      - run: |
          set ALIEN_INSTALL_TYPE=share
          cpan Alien::libtiff 
          cpan ExtUtils::Depends ExtUtils::PkgConfig Test::Deep Test::Requires Test::Simple .
```

(edit - Env vars don't persist by default.  The code to add to the path is an example of how to make it persist)

**Comment by shawnlaffan** [comment]
@PhilterPaper -

> By the way, if Alien is being used to prereq libtiff, shouldn't CPAN try to install Alien::libtiff automatically, rather than requiring me to manually initiate the install? I.e., `cpan> install Alien::libtiff` before `cpan> install Graphics::TIFF`.

This is because Alien::libtiff has yet to be added as a dependency to Makefile.PL.  I assume this is on the list of things to do.

**Comment by PhilterPaper** [comment]
OK, that would make sense. Once it's in Makefile.PL, I presume that Alien::libtiff should be treated much like any other mandatory prerequisite.

**Comment by carygravel** [comment]
> Environment variables don't persist outside the individual run calls. The set call needs to be in the same run as the cpan calls.
> 
> Something like this (I put the Alien::libtiff call on its own line for clarity only)
> 
> ```yaml
>       - run: |
>           set ALIEN_INSTALL_TYPE=share
>           cpan Alien::libtiff 
>           cpan ExtUtils::Depends ExtUtils::PkgConfig Test::Deep Test::Requires Test::Simple .
> ```

Thanks for this. Given the changes [didn't make any difference to the output](https://github.com/carygravel/graphics-tiff/actions/runs/877657596), I assume that the explanation from @plicease is the reason, that Alien isn't finding the system library.

**Comment by shawnlaffan** [comment]
> Thanks for this. Given the changes [didn't make any difference to the output](https://github.com/carygravel/graphics-tiff/actions/runs/877657596), I assume that the explanation from @plicease is the reason, that Alien isn't finding the system library.

But it is finding and using the system library.  The issue seems to be that it is not building a shared install.  

And on further checking, I had my syntax wrong.  The system is using powershell, so it needs a different syntax.  

What happens if you use:

```yaml
    - run: |
          $env:ALIEN_INSTALL_TYPE="share"
          cpan Alien::libtiff 
```

**Comment by carygravel** [comment]
> What happens if you use:
> 
> ```yaml
>     - run: |
>           $env:ALIEN_INSTALL_TYPE="share"
>           cpan Alien::libtiff 
> ```

Genius! Thanks. Now it installs libtiff v4.3.0!

**Comment by shawnlaffan** [comment]
Good to hear it all works now.  CI can be something of a rabbit hole at times...

**Comment by carygravel** [comment]
I think this issue case be closed, then. Thanks for all the help.

**Comment by shawnlaffan** [comment]
Not a problem.  PRs welcome for changes needed.  

Some of the tests in your version would be good to have, for example.  I'll open a separate issue for that.

**Comment by shawnlaffan** [comment]
@carygravel - I see you've deleted your version of Alien::libtiff.  Any chance you could submit a PR with some of the additional tests?  I seem to recall there were some in there to test the tiff images.  Or maybe I'm conflating it with tests in Graphics::TIFF.

**Comment by carygravel** [comment]
No problem. I'll work up something in the next few days.

**Comment by carygravel** [comment]
[Here's the test](https://github.com/carygravel/perl-alien-libtiff/blob/test/t/03_tools.t). It's runs locally on my Linux machine. I assume the reason it isn't passing in the Windows runner is due to Windows munging the file endings. Can you test locally?

**Comment by shawnlaffan** [comment]
The test file works fine for me with a share install.  It fails with a system install because the utility is not available.  

You can make the test conditional on ppm2tiff being in the path, for which File::Which can be used.  

It might also need a check that the ppm2tiff binary is the one associated with the libtiff dll, using some logic based on share or system install.
